vich_uploader:
    db_driver: orm

    mappings:
        profil_image:
            uri_prefix: /images/profil
            upload_destination: '%kernel.project_dir%/public/images/profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
